### ISSUE TITLE
Remove extra separator when there is no indicator.

### ISSUE THREAD

**Issue by sainnhe** [niklaas/lightline-gitdiff#5]
# Description
![pic](https://user-images.githubusercontent.com/37491630/55698063-ba10c980-59f6-11e9-917a-d71a7e508011.png)
When I'm editing a file which is 10 lines deleted, 0 lined added, 0 lines modified, `lightline#gitdiff#get()` returned value is as described in the figure above.
As you can see, there are two separators on the left and right of `-10`.
Personally, I think it might be better to remove the two separators, or add an option to allow users to remove extra separators when it's possible.

# Minimal Configuration
```vim
let g:lightline#gitdiff#indicator_added = '+'
let g:lightline#gitdiff#indicator_deleted = '-'
let g:lightline#gitdiff#indicator_modified = '*'
let g:lightline#gitdiff#separator = "\ue0bb"
```

**Comment by niklaas** [comment]
Thanks for reporting the issue. This looks like a bug to me. There shouldn't be any additional separators/characters despite those that you configured. And there shouldn't be separators if there is nothing to separate. :-) I'll fix this as soon as possible and will let you know.

**Comment by niklaas** [comment]
It's this line: https://github.com/niklaas/lightline-gitdiff/blob/381594cd099e7ae6a18363cd6bd3ec7b0e381d40/autoload/lightline/gitdiff.vim#L44

`join()` seems to insert the separator although `l:lines_added` and `l:lines_modified` are empty. This should be easy to fix by filtering the array with `{ el -> el !=# '' }`. I'll patch this later.

**Comment by niklaas** [comment]
Can you check whether pull request #6 solves the issue for you? If it does, I'll merge it into master as soon as possible.

**Comment by sainnhe** [comment]
@niklaas I've tried that, it works. Thanks!

**Comment by niklaas** [comment]
I merged the fix into master. Thanks again for your support!
